-- Primero se dropean los constraints
ALTER TABLE `KT`.`AMENITY` DROP CONSTRAINT `FK_IDHOTEL_AMENITY`;
ALTER TABLE `KT`.`AMENITYXROOM` DROP CONSTRAINT `FK_IDAMENITY_AMENITYXROOM`;
ALTER TABLE `KT`.`AMENITYXROOM` DROP CONSTRAINT `FK_IDROOM_AMENITYXROOM`;
ALTER TABLE `KT`.`CANTON` DROP CONSTRAINT `FK_IDSTATE_CANTON`;
ALTER TABLE `KT`.`DISTRICT` DROP CONSTRAINT `FK_IDCANTON_DISTRICT`;
ALTER TABLE `KT`.`EMAIL` DROP CONSTRAINT `FK_IDUSER_EMAIL`;
ALTER TABLE `KT`.`FAVORITE` DROP CONSTRAINT `FK_IDHOTEL_FAVORITE`;
ALTER TABLE `KT`.`FAVORITE` DROP CONSTRAINT `FK_IDUSER_FAVORITE`;
ALTER TABLE `KT`.`FEEDBACK` DROP CONSTRAINT `FK_IDRESERVATION_FEEDBACK`;
ALTER TABLE `KT`.`HOTEL` DROP CONSTRAINT `FK_IDCLASIFICATION_HOTEL`;
ALTER TABLE `KT`.`HOTEL` DROP CONSTRAINT `FK_IDDISCOUNT_HOTEL`;
ALTER TABLE `KT`.`HOTEL` DROP CONSTRAINT `FK_IDDISTRICT_HOTEL`;
ALTER TABLE `KT`.`PAYMENTMETHODXHOTEL` DROP CONSTRAINT `FK_IDHOTEL_PAYMENTMXHOTEL`;
 ALTER TABLE `KT`.`PAYMENTMETHODXHOTEL` DROP CONSTRAINT `FK_IDPAYMENTM_PAYMENTMXHOTEL`;
ALTER TABLE `KT`.`PHOTO` DROP CONSTRAINT `FK_IDHOTEL_PHOTO`;
ALTER TABLE `KT`.`RESERVATION` DROP CONSTRAINT `FK_IDPAYMENT_RESERVATION`;
ALTER TABLE `KT`.`RESERVATION` DROP CONSTRAINT `FK_IDPENALTY_RESERVATION`;
ALTER TABLE `KT`.`RESERVATION` DROP CONSTRAINT `FK_IDUSER_RESERVATION`;
ALTER TABLE `KT`.`RESERVATIONXROOM` DROP CONSTRAINT `FK_IDDISCOUNT_RESERVXROOM`;
ALTER TABLE `KT`.`RESERVATIONXROOM` DROP CONSTRAINT `FK_IDRESERVATION_RESERVXROOM`;
ALTER TABLE `KT`.`RESERVATIONXROOM` DROP CONSTRAINT `FK_IDROOM_RESERVXROOM`;
ALTER TABLE `KT`.`REVIEW` DROP CONSTRAINT `FK_IDRESERVATION_REVIEW`;
ALTER TABLE `KT`.`ROOM` DROP CONSTRAINT `FK_IDHOTEL_ROOM`;
ALTER TABLE `KT`.`ROOM` DROP CONSTRAINT `FK_IDROOMCATEGORY_ROOM`;
ALTER TABLE `KT`.`STATE` DROP CONSTRAINT `FK_IDCOUNTRY_STATE`;
ALTER TABLE `KT`.`USERS` DROP CONSTRAINT `FK_IDDISTRICT_USER`;
ALTER TABLE `KT`.`USERS` DROP CONSTRAINT `FK_IDGENDER_USER`;
ALTER TABLE `KT`.`USERS` DROP CONSTRAINT `FK_IDHOTELADMIN_USER`;
ALTER TABLE `KT`.`USERS` DROP CONSTRAINT `FK_IDTYPE_USER`;
ALTER TABLE `KT`.`USERS` DROP CONSTRAINT `FK_IDUSERTYPE_USER`;
ALTER TABLE `KT`.`USERXNATIONALITY` DROP CONSTRAINT `FK_IDNATIONALITY_USERXNAT`;
ALTER TABLE `KT`.`USERXNATIONALITY` DROP CONSTRAINT `FK_IDUSER_USERXNAT`;
ALTER TABLE `KT`.`USERXPHONENUMBER` DROP CONSTRAINT `FK_IDPHONENUMBER_USERXPHONE`;
ALTER TABLE `KT`.`USERXPHONENUMBER` DROP CONSTRAINT `FK_IDUSER_USERXPHONE`;

-- Segundo se alteran las tablas
ALTER TABLE `kt`.`amenity` 
CHANGE COLUMN `idamenity` `idamenity` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL ;

ALTER TABLE `kt`.`feedback` 
CHANGE COLUMN `IDFEEDBACK` `IDFEEDBACK` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL ;

ALTER TABLE `kt`.`gender`
CHANGE COLUMN `IDgender` `IDgender` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL ;

ALTER TABLE `kt`.`hotel` 
CHANGE COLUMN `IDHOTEL` `IDHOTEL` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSERS` `CREATIONUSERS` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSERS` `MODUSERS` VARCHAR(100) NULL DEFAULT NULL ;

ALTER TABLE `kt`.`hotelclasification` 
CHANGE COLUMN `IDhotelclasification` `IDhotelclasification` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL ;

ALTER TABLE `kt`.`idtype` 
CHANGE COLUMN `IDidtype` `IDidtype` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL ;

ALTER TABLE `kt`.`nationality` 
CHANGE COLUMN `IDnationality` `IDnationality` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL ;

ALTER TABLE `kt`.`parameter` 
CHANGE COLUMN `IDparameter` `IDparameter` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL ;

ALTER TABLE `kt`.`amenityxroom` 
CHANGE COLUMN `IDamenityxroom` `IDamenityxroom` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL ;

ALTER TABLE `kt`.`canton` 
CHANGE COLUMN `IDcanton` `IDcanton` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL ;

ALTER TABLE `kt`.`country` 
CHANGE COLUMN `IDcountry` `IDcountry` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL ;

ALTER TABLE `kt`.`discount` 
CHANGE COLUMN `IDdiscount` `IDdiscount` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL ;

ALTER TABLE `kt`.`district` 
CHANGE COLUMN `IDdistrict` `IDdistrict` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL ;

ALTER TABLE `kt`.`email` 
CHANGE COLUMN `IDemail` `IDemail` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL ;

ALTER TABLE `kt`.`favorite` 
CHANGE COLUMN `IDfavorite` `IDfavorite` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL;

ALTER TABLE `kt`.`paymentmethod` 
CHANGE COLUMN `IDpaymentmethod` `IDpaymentmethod` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL;

ALTER TABLE `kt`.`paymentmethodxhotel` 
CHANGE COLUMN `IDpaymentmethodxhotel` `IDpaymentmethodxhotel` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL;

ALTER TABLE `kt`.`penalty` 
CHANGE COLUMN `IDpenalty` `IDpenalty` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL;

ALTER TABLE `kt`.`phonenumber` 
CHANGE COLUMN `IDphonenumber` `IDphonenumber` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL;

ALTER TABLE `kt`.`photo` 
CHANGE COLUMN `IDphoto` `IDphoto` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL;

ALTER TABLE `kt`.`reservation` 
CHANGE COLUMN `IDreservation` `IDreservation` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL;

ALTER TABLE `kt`.`reservationxroom` 
CHANGE COLUMN `IDreservationxroom` `IDreservationxroom` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL;

ALTER TABLE `kt`.`review` 
CHANGE COLUMN `IDreview` `IDreview` INT AUTO_INCREMENT,
AUTO_INCREMENT = 11,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL;

ALTER TABLE `kt`.`room` 
CHANGE COLUMN `IDroom` `IDroom` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL;

ALTER TABLE `kt`.`roomcategory` 
CHANGE COLUMN `IDroomcategory` `IDroomcategory` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL;

ALTER TABLE `kt`.`state` 
CHANGE COLUMN `IDstate` `IDstate` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL;

ALTER TABLE `kt`.`users` 
CHANGE COLUMN `IDuser` `IDuser` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL;

ALTER TABLE `kt`.`usertype` 
CHANGE COLUMN `IDusertype` `IDusertype` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL;

ALTER TABLE `kt`.`userxnationality` 
CHANGE COLUMN `IDuserxnationality` `IDuserxnationality` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL;

ALTER TABLE `kt`.`userxphonenumber` 
CHANGE COLUMN `IDuserxphonenumber` `IDuserxphonenumber` INT AUTO_INCREMENT,
CHANGE COLUMN `CREATIONUSER` `CREATIONUSER` VARCHAR(100) NULL DEFAULT NULL,
CHANGE COLUMN `MODUSER` `MODUSER` VARCHAR(100) NULL DEFAULT NULL;

-- Tercero, se vuelven a crear los constraints

  ALTER TABLE `KT`.`AMENITY` ADD CONSTRAINT `FK_IDHOTEL_AMENITY` FOREIGN KEY (`IDHOTEL`)
	  REFERENCES `KT`.`HOTEL` (`IDHOTEL`);

  ALTER TABLE `KT`.`AMENITYXROOM` ADD CONSTRAINT `FK_IDAMENITY_AMENITYXROOM` FOREIGN KEY (`IDAMENITY`)
	  REFERENCES `KT`.`AMENITY` (`IDAMENITY`);
 
  ALTER TABLE `KT`.`AMENITYXROOM` ADD CONSTRAINT `FK_IDROOM_AMENITYXROOM` FOREIGN KEY (`IDROOM`)
	  REFERENCES `KT`.`ROOM` (`IDROOM`);

  ALTER TABLE `KT`.`CANTON` ADD CONSTRAINT `FK_IDSTATE_CANTON` FOREIGN KEY (`IDSTATE`)
	  REFERENCES `KT`.`STATE` (`IDSTATE`);

  ALTER TABLE `KT`.`DISTRICT` ADD CONSTRAINT `FK_IDCANTON_DISTRICT` FOREIGN KEY (`IDCANTON`)
	  REFERENCES `KT`.`CANTON` (`IDCANTON`);

  ALTER TABLE `KT`.`EMAIL` ADD CONSTRAINT `FK_IDUSER_EMAIL` FOREIGN KEY (`IDUSER`)
	  REFERENCES `KT`.`USERS` (`IDUSER`);

  ALTER TABLE `KT`.`FAVORITE` ADD CONSTRAINT `FK_IDHOTEL_FAVORITE` FOREIGN KEY (`IDHOTEL`)
	  REFERENCES `KT`.`HOTEL` (`IDHOTEL`);
 
  ALTER TABLE `KT`.`FAVORITE` ADD CONSTRAINT `FK_IDUSER_FAVORITE` FOREIGN KEY (`IDUSER`)
	  REFERENCES `KT`.`USERS` (`IDUSER`);

  ALTER TABLE `KT`.`FEEDBACK` ADD CONSTRAINT `FK_IDRESERVATION_FEEDBACK` FOREIGN KEY (`IDRESERVATION`)
	  REFERENCES `KT`.`RESERVATION` (`IDRESERVATION`);

  ALTER TABLE `KT`.`HOTEL` ADD CONSTRAINT `FK_IDCLASIFICATION_HOTEL` FOREIGN KEY (`IDCLASIFICATION`)
	  REFERENCES `KT`.`HOTELCLASIFICATION` (`IDHOTELCLASIFICATION`);
 
  ALTER TABLE `KT`.`HOTEL` ADD CONSTRAINT `FK_IDDISCOUNT_HOTEL` FOREIGN KEY (`IDDISCOUNT`)
	  REFERENCES `KT`.`DISCOUNT` (`IDDISCOUNT`);
 
  ALTER TABLE `KT`.`HOTEL` ADD CONSTRAINT `FK_IDDISTRICT_HOTEL` FOREIGN KEY (`IDDISTRICT`)
	  REFERENCES `KT`.`DISTRICT` (`IDDISTRICT`);

  ALTER TABLE `KT`.`PAYMENTMETHODXHOTEL` ADD CONSTRAINT `FK_IDHOTEL_PAYMENTMXHOTEL` FOREIGN KEY (`IDHOTEL`)
	  REFERENCES `KT`.`HOTEL` (`IDHOTEL`);
 
  ALTER TABLE `KT`.`PAYMENTMETHODXHOTEL` ADD CONSTRAINT `FK_IDPAYMENTM_PAYMENTMXHOTEL` FOREIGN KEY (`IDPAYMENTMETHOD`)
	  REFERENCES `KT`.`PAYMENTMETHOD` (`IDPAYMENTMETHOD`);

  ALTER TABLE `KT`.`PHOTO` ADD CONSTRAINT `FK_IDHOTEL_PHOTO` FOREIGN KEY (`IDHOTEL`)
	  REFERENCES `KT`.`HOTEL` (`IDHOTEL`);

  ALTER TABLE `KT`.`RESERVATION` ADD CONSTRAINT `FK_IDPAYMENT_RESERVATION` FOREIGN KEY (`IDPAYMENT`)
	  REFERENCES `KT`.`PAYMENTMETHOD` (`IDPAYMENTMETHOD`);
 
  ALTER TABLE `KT`.`RESERVATION` ADD CONSTRAINT `FK_IDPENALTY_RESERVATION` FOREIGN KEY (`IDPENALTY`)
	  REFERENCES `KT`.`PENALTY` (`IDPENALTY`);
 
  ALTER TABLE `KT`.`RESERVATION` ADD CONSTRAINT `FK_IDUSER_RESERVATION` FOREIGN KEY (`IDUSER`)
	  REFERENCES `KT`.`USERS` (`IDUSER`);

  ALTER TABLE `KT`.`RESERVATIONXROOM` ADD CONSTRAINT `FK_IDDISCOUNT_RESERVXROOM` FOREIGN KEY (`IDDISCOUNT`)
	  REFERENCES `KT`.`DISCOUNT` (`IDDISCOUNT`);
 
  ALTER TABLE `KT`.`RESERVATIONXROOM` ADD CONSTRAINT `FK_IDRESERVATION_RESERVXROOM` FOREIGN KEY (`IDRESERVATION`)
	  REFERENCES `KT`.`RESERVATION` (`IDRESERVATION`);
 
  ALTER TABLE `KT`.`RESERVATIONXROOM` ADD CONSTRAINT `FK_IDROOM_RESERVXROOM` FOREIGN KEY (`IDROOM`)
	  REFERENCES `KT`.`ROOM` (`IDROOM`);

  ALTER TABLE `KT`.`REVIEW` ADD CONSTRAINT `FK_IDRESERVATION_REVIEW` FOREIGN KEY (`IDRESERVATION`)
	  REFERENCES `KT`.`RESERVATION` (`IDRESERVATION`);

  ALTER TABLE `KT`.`ROOM` ADD CONSTRAINT `FK_IDHOTEL_ROOM` FOREIGN KEY (`IDHOTEL`)
	  REFERENCES `KT`.`HOTEL` (`IDHOTEL`);
 
  ALTER TABLE `KT`.`ROOM` ADD CONSTRAINT `FK_IDROOMCATEGORY_ROOM` FOREIGN KEY (`IDROOMCATEGORY`)
	  REFERENCES `KT`.`ROOMCATEGORY` (`IDROOMCATEGORY`);

  ALTER TABLE `KT`.`STATE` ADD CONSTRAINT `FK_IDCOUNTRY_STATE` FOREIGN KEY (`IDCOUNTRY`)
	  REFERENCES `KT`.`COUNTRY` (`IDCOUNTRY`);

  ALTER TABLE `KT`.`USERS` ADD CONSTRAINT `FK_IDDISTRICT_USER` FOREIGN KEY (`IDDISTRICT`)
	  REFERENCES `KT`.`DISTRICT` (`IDDISTRICT`);
 
  ALTER TABLE `KT`.`USERS` ADD CONSTRAINT `FK_IDGENDER_USER` FOREIGN KEY (`IDGENDER`)
	  REFERENCES `KT`.`GENDER` (`IDGENDER`);
 
  ALTER TABLE `KT`.`USERS` ADD CONSTRAINT `FK_IDHOTELADMIN_USER` FOREIGN KEY (`IDHOTELADMIN`)
	  REFERENCES `KT`.`HOTEL` (`IDHOTEL`);
 
  ALTER TABLE `KT`.`USERS` ADD CONSTRAINT `FK_IDTYPE_USER` FOREIGN KEY (`IDTYPE`)
	  REFERENCES `KT`.`IDTYPE` (`IDIDTYPE`);
 
  ALTER TABLE `KT`.`USERS` ADD CONSTRAINT `FK_IDUSERTYPE_USER` FOREIGN KEY (`IDUSERTYPE`)
	  REFERENCES `KT`.`USERTYPE` (`IDUSERTYPE`);

  ALTER TABLE `KT`.`USERXNATIONALITY` ADD CONSTRAINT `FK_IDNATIONALITY_USERXNAT` FOREIGN KEY (`IDNATIONALITY`)
	  REFERENCES `KT`.`NATIONALITY` (`IDNATIONALITY`);
 
  ALTER TABLE `KT`.`USERXNATIONALITY` ADD CONSTRAINT `FK_IDUSER_USERXNAT` FOREIGN KEY (`IDUSER`)
	  REFERENCES `KT`.`USERS` (`IDUSER`);

  ALTER TABLE `KT`.`USERXPHONENUMBER` ADD CONSTRAINT `FK_IDPHONENUMBER_USERXPHONE` FOREIGN KEY (`IDPHONENUMBER`)
	  REFERENCES `KT`.`PHONENUMBER` (`IDPHONENUMBER`);
 
  ALTER TABLE `KT`.`USERXPHONENUMBER` ADD CONSTRAINT `FK_IDUSER_USERXPHONE` FOREIGN KEY (`IDUSER`)
	  REFERENCES `KT`.`USERS` (`IDUSER`);
      
-- Extras ya que estamos
UPDATE kt.nationality
SET Name = 'Costarrican'
WHERE idNationality = 1;
UPDATE kt.nationality
SET Name = 'American'
WHERE idNationality = 2;