/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AmmenityController;
import Controller.ReviewController;
import Model.AmenityModel;
import Model.HotelModel;
import Model.ReservationModel;
import Model.Review;
import Model.UserModel;
import View.Admin.admin;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author guzka
 */
public class MainWindowHotel extends javax.swing.JFrame {

    private final String imagesPath = "C:\\Users\\guzka\\Documents\\GitHub\\ProyectoBD\\src\\main\\java\\view\\images";
    private final File[] images = new File(imagesPath).listFiles();
    private int currentIndex = 0;
    HotelModel hotel;
    UserModel user;

    public MainWindowHotel(HotelModel hotel, UserModel user) {
        initComponents();
        adminZoneButton.setVisible(false);
        //changeImage();
        Timer timer = new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // changeImage();
            }
        });
        timer.start();
        setLocationRelativeTo(this);
        this.hotel = hotel;
        this.user = user;
        setHotelInfo(hotel);
        //setDefaultCloseOperation(2);
        if(user.getIdUserType()==2){
            adminZoneButton.setVisible(true);
        }

    }

    void setHotelInfo(HotelModel hotel) {
        this.hotelName.setText(hotel.getName());
        //this.clasification1.setText(hotel.getClasification() + "");
        this.country.setText(hotel.getCountry());
        this.state.setText(hotel.getState());
        this.district.setText(hotel.getDistrict());
        this.discount.setText(hotel.getDiscount() + "");
        this.canton.setText(hotel.getCanton());
    //    this.clasification1.setText(hotel.getClasification());
        getHotelReviews(hotel.getIdHotel());
        getHotelAmmenities(hotel.getIdHotel());
        
    }

    private void changeImage() {
        if (images.length == 0) {
            return;
        }
        ImageIcon imageIcon = new ImageIcon(images[currentIndex].getAbsolutePath());
        //jLabel1.setIcon(imageIcon);
        currentIndex = (currentIndex + 1) % images.length;
    }

    private void getHotelReviews(int idHotel) {
        ArrayList<Review> reviews = ReviewController.getReviews(idHotel);
        for (Review r : reviews) {
            listReview.add(r.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adminZoneButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hotelName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        country = new javax.swing.JTextField();
        state = new javax.swing.JTextField();
        canton = new javax.swing.JTextField();
        discount = new javax.swing.JTextField();
        district = new javax.swing.JTextField();
        listReview = new java.awt.List();
        book1 = new javax.swing.JButton();
        listAmmenity = new java.awt.List();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(50, 70, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminZoneButton.setBackground(new java.awt.Color(240, 248, 255));
        adminZoneButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        adminZoneButton.setText("Admin Zone");
        adminZoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminZoneButtonActionPerformed(evt);
            }
        });
        jPanel1.add(adminZoneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 248, 255));
        jLabel8.setText("REVIEWS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 248, 255));
        jLabel7.setText("DISCOUNT AVAILABLE :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        hotelName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        hotelName.setForeground(new java.awt.Color(240, 248, 255));
        hotelName.setText("HOTEL NAME");
        jPanel1.add(hotelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 248, 255));
        jLabel5.setText("DISTRICT");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 248, 255));
        jLabel4.setText("STATE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 248, 255));
        jLabel3.setText("COUNTRY");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));
        jPanel1.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 206, -1));
        jPanel1.add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 206, -1));
        jPanel1.add(canton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 206, -1));
        jPanel1.add(discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 206, -1));
        jPanel1.add(district, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 206, -1));
        jPanel1.add(listReview, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 170, 290));

        book1.setBackground(new java.awt.Color(240, 248, 255));
        book1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        book1.setText("Book");
        book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book1ActionPerformed(evt);
            }
        });
        jPanel1.add(book1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 124, 46));
        jPanel1.add(listAmmenity, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 170, 290));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 248, 255));
        jLabel9.setText("AMENITIES");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 248, 255));
        jLabel6.setText("CANTON");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminZoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminZoneButtonActionPerformed
        new admin(this.hotel,this.user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adminZoneButtonActionPerformed

    private void book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book1ActionPerformed
        // TODO add your handling code here:
        // pasarle hotel como parametro
        new ViewMakeReservation(this.user,this.hotel,this).setVisible(true);
    }//GEN-LAST:event_book1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminZoneButton;
    private javax.swing.JButton book1;
    private javax.swing.JTextField canton;
    private javax.swing.JTextField country;
    private javax.swing.JTextField discount;
    private javax.swing.JTextField district;
    private javax.swing.JLabel hotelName;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private java.awt.List listAmmenity;
    private java.awt.List listReview;
    private javax.swing.JTextField state;
    // End of variables declaration//GEN-END:variables

    private void getHotelAmmenities(int idHotel) {
        ArrayList<AmenityModel> ammenities = AmmenityController.getAmenitiesByHotel(idHotel);
        for (AmenityModel a : ammenities) {
            listAmmenity.add(a.getName());
        }
    }

}
