/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AmmenityController;
import Controller.ReviewController;
import Model.AmenityModel;
import Model.HotelModel;
import Model.ReservationModel;
import Model.Review;
import Model.UserModel;
import View.Admin.AdminHotel;
import View.ViewMakeReservation;
import View.ViewMakeReservation;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author guzka
 */
public class ViewHotel extends javax.swing.JFrame {

    private final String imagesPath = "C:\\Users\\guzka\\Documents\\GitHub\\ProyectoBD\\src\\main\\java\\view\\images";
    private final File[] images = new File(imagesPath).listFiles();
    private int currentIndex = 0;
    HotelModel hotel;
    UserModel user;

    public ViewHotel(HotelModel hotel, UserModel user) {
        initComponents();
        //adminZoneButton.setVisible(false);
        //changeImage();
        Timer timer = new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // changeImage();
            }
        });
        timer.start();
        setLocationRelativeTo(this);
        this.hotel = hotel;
        this.user = user;
        setHotelInfo(hotel);
        //setDefaultCloseOperation(2);
      

    }

    void setHotelInfo(HotelModel hotel) {
        this.hotelName1.setText(hotel.getName());
        this.regLabel.setText("Reg Date: " + hotel.getRegisterDate().toLocaleString());
        this.regLabel1.setText("Classi: " +hotel.getClasification());
        getHotelReviews(hotel.getIdHotel());
        getHotelAmmenities(hotel.getIdHotel());
        
    }

    private void changeImage() {
        if (images.length == 0) {
            return;
        }
        ImageIcon imageIcon = new ImageIcon(images[currentIndex].getAbsolutePath());
        //jLabel1.setIcon(imageIcon);
        currentIndex = (currentIndex + 1) % images.length;
    }

    private void getHotelReviews(int idHotel) {
        ArrayList<Review> reviews = ReviewController.getReviews(idHotel);
        for (Review r : reviews) {
            listReview.add(r.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        regLabel = new javax.swing.JLabel();
        listReview = new java.awt.List();
        book1 = new javax.swing.JButton();
        listAmmenity = new java.awt.List();
        jLabel9 = new javax.swing.JLabel();
        listReview1 = new java.awt.List();
        hotelName1 = new javax.swing.JLabel();
        regLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(50, 70, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 248, 255));
        jLabel8.setText("REVIEWS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 248, 255));
        jLabel7.setText("DISCOUNTS :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        regLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        regLabel.setForeground(new java.awt.Color(240, 248, 255));
        regLabel.setText("Classi:");
        jPanel1.add(regLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));
        jPanel1.add(listReview, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 150, 290));

        book1.setBackground(new java.awt.Color(240, 248, 255));
        book1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        book1.setText("Book");
        book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book1ActionPerformed(evt);
            }
        });
        jPanel1.add(book1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 124, 46));
        jPanel1.add(listAmmenity, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 150, 290));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 248, 255));
        jLabel9.setText("AMENITIES");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));
        jPanel1.add(listReview1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 170, 290));

        hotelName1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        hotelName1.setForeground(new java.awt.Color(240, 248, 255));
        hotelName1.setText("HOTEL NAME");
        jPanel1.add(hotelName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        regLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        regLabel1.setForeground(new java.awt.Color(240, 248, 255));
        regLabel1.setText("Reg Date");
        jPanel1.add(regLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 540, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book1ActionPerformed
        // TODO add your handling code here:
        // pasarle hotel como parametro
        new ViewMakeReservation(this.user,this.hotel,this).setVisible(true);
    }//GEN-LAST:event_book1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton book1;
    private javax.swing.JLabel hotelName1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.List listAmmenity;
    private java.awt.List listReview;
    private java.awt.List listReview1;
    private javax.swing.JLabel regLabel;
    private javax.swing.JLabel regLabel1;
    // End of variables declaration//GEN-END:variables

    private void getHotelAmmenities(int idHotel) {
        ArrayList<AmenityModel> ammenities = AmmenityController.getAmenitiesByHotel(idHotel);
        for (AmenityModel a : ammenities) {
            listAmmenity.add(a.getName());
        }
    }

}
