/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Master;

import View.Admin.Queries.Query02OfferView;
import View.Admin.*;
import Controller.AmmenityController;
import Model.AmenityModel;
import Model.HotelModel;
import Model.Review;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josep
 */
public class master extends javax.swing.JFrame {
    
    DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form admin
     */
    public master() {
        initComponents();
        
        
       
        // Crea una instancia de la ventana Discount
// Configura otros aspectos de la ventana Discount si es necesario


        // Obtiene el panel en el que se insertará la ventana
 
    }
    
    /**
     * Creates new form admin
     */
    public master(HotelModel hotel) {
        initComponents();
        this.hotel = hotel;
        loadAmmenities();
         setLocationRelativeTo(this);
        setDefaultCloseOperation(2);
    }

    void loadAmmenities(){
        ArrayList<AmenityModel> amenities = AmmenityController.getAmenities();
          for (AmenityModel r : amenities) {
           //jComboBox2.addItem(r.getName().toString());
          }
    }
    HotelModel hotel;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        admin = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        inquieriess = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        parameter1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        PanelDeleteHotel = new javax.swing.JPanel();
        PanelParameters = new javax.swing.JPanel();
        PanelCreateHotel = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        roomw1 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        reserva1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        reserva2 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        roomw2 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        roomw3 = new javax.swing.JLabel();
        roomw4 = new javax.swing.JLabel();
        roomw5 = new javax.swing.JLabel();
        roomw6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        roomw7 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        realPanelconsultations = new javax.swing.JPanel();
        jPanel59 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        PanelAdmin = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        book1 = new javax.swing.JButton();
        book3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(184, 210, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(50, 70, 80));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(50, 70, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/icons/User-Profile-26_1.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        admin.setBackground(new java.awt.Color(0, 0, 0));
        admin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setText("        Admin");
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(admin, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        sidepanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 270, 40));

        jPanel7.setBackground(new java.awt.Color(50, 70, 80));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Back to Main");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons/Logout-26.png"))); // NOI18N
        jLabel11.setText("jLabel11");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11))
        );

        sidepanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 270, 80));

        jPanel8.setBackground(new java.awt.Color(50, 70, 80));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons/Discount-26.png"))); // NOI18N

        jLabel7.setBackground(new java.awt.Color(65, 65, 65));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("      Create Hotel");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 270, 40));

        jPanel10.setBackground(new java.awt.Color(50, 70, 80));
        jPanel10.setPreferredSize(new java.awt.Dimension(176, 25));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        sidepanel.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 270, 30));

        jPanel12.setBackground(new java.awt.Color(65, 65, 65));
        jPanel12.setPreferredSize(new java.awt.Dimension(176, 25));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons/Restaurant-26.png"))); // NOI18N
        jLabel5.setText("jLabel2");

        inquieriess.setBackground(new java.awt.Color(27, 74, 97));
        inquieriess.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inquieriess.setForeground(new java.awt.Color(255, 255, 255));
        inquieriess.setText("        inquiries");
        inquieriess.setToolTipText("");
        inquieriess.setPreferredSize(new java.awt.Dimension(176, 25));
        inquieriess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inquieriessMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inquieriess, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inquieriess, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidepanel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 270, 40));

        jLabel8.setBackground(new java.awt.Color(44, 120, 156));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("              MASTER ZONE");
        sidepanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 240, 60));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons/sinfondo (1).png"))); // NOI18N
        jLabel17.setText("jLabel17");
        sidepanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 120, 70));

        parameter1.setBackground(new java.awt.Color(0, 0, 0));
        parameter1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        parameter1.setForeground(new java.awt.Color(255, 255, 255));
        parameter1.setText("        Parameters");
        parameter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parameter1MouseClicked(evt);
            }
        });
        sidepanel.add(parameter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 184, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons/Sleep-01-26.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        sidepanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 34, -1));

        jPanel1.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 570));

        jPanel2.setBackground(new java.awt.Color(65, 65, 65));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 690, 60));

        jPanel3.setLayout(new java.awt.CardLayout());

        PanelDeleteHotel.setBackground(new java.awt.Color(255, 255, 225));

        javax.swing.GroupLayout PanelDeleteHotelLayout = new javax.swing.GroupLayout(PanelDeleteHotel);
        PanelDeleteHotel.setLayout(PanelDeleteHotelLayout);
        PanelDeleteHotelLayout.setHorizontalGroup(
            PanelDeleteHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        PanelDeleteHotelLayout.setVerticalGroup(
            PanelDeleteHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel3.add(PanelDeleteHotel, "card3");

        PanelParameters.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelParametersLayout = new javax.swing.GroupLayout(PanelParameters);
        PanelParameters.setLayout(PanelParametersLayout);
        PanelParametersLayout.setHorizontalGroup(
            PanelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        PanelParametersLayout.setVerticalGroup(
            PanelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel3.add(PanelParameters, "card4");

        PanelCreateHotel.setBackground(new java.awt.Color(118, 131, 138));

        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(50, 70, 80));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(240, 248, 255));
        jPanel16.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 111, 460, -1));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/icons/Maps-26.png"))); // NOI18N
        jPanel16.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 90, -1, -1));

        roomw1.setBackground(new java.awt.Color(0, 0, 0));
        roomw1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomw1.setForeground(new java.awt.Color(255, 255, 255));
        roomw1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomw1MouseClicked(evt);
            }
        });
        jPanel16.add(roomw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/icons/Date-26 (1).png"))); // NOI18N
        jLabel35.setText("jLabel2");
        jPanel16.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 34, -1));

        reserva1.setBackground(new java.awt.Color(65, 65, 65));
        reserva1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reserva1.setForeground(new java.awt.Color(255, 255, 255));
        reserva1.setText("Register Date");
        reserva1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reserva1MouseClicked(evt);
            }
        });
        jPanel16.add(reserva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 100, 30));
        jPanel16.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 97, 145, -1));

        reserva2.setBackground(new java.awt.Color(65, 65, 65));
        reserva2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reserva2.setForeground(new java.awt.Color(255, 255, 255));
        reserva2.setText("Name");
        reserva2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reserva2MouseClicked(evt);
            }
        });
        jPanel16.add(reserva2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 90, 100, 30));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/icons/Tag-26.png"))); // NOI18N
        jLabel36.setText("jLabel4");
        jPanel16.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 90, 34, -1));

        jLabel37.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(50, 70, 80));
        jLabel37.setText("CREATE HOTEL");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 70));

        roomw2.setBackground(new java.awt.Color(0, 0, 0));
        roomw2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomw2.setForeground(new java.awt.Color(255, 255, 255));
        roomw2.setText("District");
        roomw2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomw2MouseClicked(evt);
            }
        });
        jPanel16.add(roomw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 64, 31));

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons/Discount-26.png"))); // NOI18N
        jPanel16.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        roomw3.setBackground(new java.awt.Color(0, 0, 0));
        roomw3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomw3.setForeground(new java.awt.Color(255, 255, 255));
        roomw3.setText("Location : ");
        roomw3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomw3MouseClicked(evt);
            }
        });
        jPanel16.add(roomw3, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 90, 98, 31));

        roomw4.setBackground(new java.awt.Color(0, 0, 0));
        roomw4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomw4.setForeground(new java.awt.Color(255, 255, 255));
        roomw4.setText("Country");
        roomw4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomw4MouseClicked(evt);
            }
        });
        jPanel16.add(roomw4, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 139, 64, 31));

        roomw5.setBackground(new java.awt.Color(0, 0, 0));
        roomw5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomw5.setForeground(new java.awt.Color(255, 255, 255));
        roomw5.setText("State");
        roomw5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomw5MouseClicked(evt);
            }
        });
        jPanel16.add(roomw5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 64, 30));

        roomw6.setBackground(new java.awt.Color(0, 0, 0));
        roomw6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomw6.setForeground(new java.awt.Color(255, 255, 255));
        roomw6.setText("Canton");
        roomw6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomw6MouseClicked(evt);
            }
        });
        jPanel16.add(roomw6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 64, 31));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel16.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 160, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel16.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 160, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel16.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 160, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel16.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 160, -1));

        roomw7.setBackground(new java.awt.Color(0, 0, 0));
        roomw7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roomw7.setForeground(new java.awt.Color(255, 255, 255));
        roomw7.setText("Clasification");
        roomw7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomw7MouseClicked(evt);
            }
        });
        jPanel16.add(roomw7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel16.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 140, -1));
        jPanel16.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 150, 40));

        jPanel15.add(jPanel16, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout PanelCreateHotelLayout = new javax.swing.GroupLayout(PanelCreateHotel);
        PanelCreateHotel.setLayout(PanelCreateHotelLayout);
        PanelCreateHotelLayout.setHorizontalGroup(
            PanelCreateHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(PanelCreateHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelCreateHotelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelCreateHotelLayout.setVerticalGroup(
            PanelCreateHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(PanelCreateHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelCreateHotelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(PanelCreateHotel, "card5");

        realPanelconsultations.setBackground(new java.awt.Color(255, 255, 225));
        realPanelconsultations.setForeground(new java.awt.Color(255, 153, 51));

        jPanel59.setBackground(new java.awt.Color(50, 70, 80));

        jLabel19.setBackground(new java.awt.Color(240, 248, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 248, 255));
        jLabel19.setText("AVAILABLE CONSULTATIONS");

        jButton6.setBackground(new java.awt.Color(240, 248, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(50, 70, 80));
        jButton6.setText("OFFERS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(240, 248, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(50, 70, 80));
        jButton7.setText("PEOPLE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(240, 248, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(50, 70, 80));
        jButton8.setText("RATINGS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(240, 248, 255));
        jButton9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(50, 70, 80));
        jButton9.setText("SALES");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel59Layout = new javax.swing.GroupLayout(jPanel59);
        jPanel59.setLayout(jPanel59Layout);
        jPanel59Layout.setHorizontalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel59Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel59Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel59Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(113, 113, 113))
        );
        jPanel59Layout.setVerticalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel59Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(43, 43, 43)
                .addGroup(jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton7))
                .addGap(70, 70, 70)
                .addGroup(jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton9))
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout realPanelconsultationsLayout = new javax.swing.GroupLayout(realPanelconsultations);
        realPanelconsultations.setLayout(realPanelconsultationsLayout);
        realPanelconsultationsLayout.setHorizontalGroup(
            realPanelconsultationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(realPanelconsultationsLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        realPanelconsultationsLayout.setVerticalGroup(
            realPanelconsultationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, realPanelconsultationsLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jPanel59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        jPanel3.add(realPanelconsultations, "card6");

        PanelAdmin.setBackground(new java.awt.Color(50, 70, 80));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 248, 255));
        jLabel9.setText("ADMIN");

        book1.setBackground(new java.awt.Color(240, 248, 255));
        book1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        book1.setText("CREATE ADMIN");
        book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book1ActionPerformed(evt);
            }
        });

        book3.setBackground(new java.awt.Color(240, 248, 255));
        book3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        book3.setText("DELETE ADMIN");
        book3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAdminLayout = new javax.swing.GroupLayout(PanelAdmin);
        PanelAdmin.setLayout(PanelAdminLayout);
        PanelAdminLayout.setHorizontalGroup(
            PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminLayout.createSequentialGroup()
                .addGroup(PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdminLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(book1)
                        .addGap(88, 88, 88)
                        .addComponent(book3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAdminLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel9)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        PanelAdminLayout.setVerticalGroup(
            PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel9)
                .addGap(51, 51, 51)
                .addGroup(PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(312, Short.MAX_VALUE))
        );

        jPanel3.add(PanelAdmin, "card7");

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 690, 510));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inquieriessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inquieriessMouseClicked
        inquieriess.setBackground(new  java.awt.Color(44 , 59 , 66));
        realPanelconsultations.setVisible(true);
        
        
        
        
//        delete.setBackground(new  java.awt.Color(34 ,45,49));
        PanelDeleteHotel.setVisible(false);
        
        
        
        admin.setBackground(new  java.awt.Color(34 ,45,49));
        PanelParameters.setVisible(false);
        
        jLabel7.setBackground(new  java.awt.Color(34 ,45,49));
        PanelCreateHotel.setVisible(false);
        
        admin.setBackground(new  java.awt.Color(34 ,45,49));
        PanelAdmin.setVisible(false);
        
        
    }//GEN-LAST:event_inquieriessMouseClicked

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
             inquieriess.setBackground(new  java.awt.Color(34 ,45,49));
        realPanelconsultations.setVisible(false); 
        
        
        
        
//        delete.setBackground(new  java.awt.Color(34 ,45,49));
        PanelDeleteHotel.setVisible(false);
        
        
        
        admin.setBackground(new  java.awt.Color(34 ,45,49));
        PanelParameters.setVisible(false);
        
        jLabel7.setBackground(new  java.awt.Color(34 ,45,49));
        PanelCreateHotel.setVisible(false);
        
        inquieriess.setBackground(new  java.awt.Color(34 ,45,49));
        realPanelconsultations.setVisible(false);
        
        
        admin.setBackground(new  java.awt.Color(44 , 59 , 66));
        PanelAdmin.setVisible(true);
        
        

    }//GEN-LAST:event_adminMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       this.setVisible(false);
               
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        
        
        inquieriess.setBackground(new  java.awt.Color(34 ,45,49));
        realPanelconsultations.setVisible(false); 
        
        
        
        
        admin.setBackground(new  java.awt.Color(34 ,45,49));
        PanelDeleteHotel.setVisible(false);
        
        
        
//        delete.setBackground(new  java.awt.Color(34 ,45,49));
        PanelDeleteHotel.setVisible(false); 
        
        
        jLabel7.setBackground(new  java.awt.Color(44 , 59 , 66));
        PanelCreateHotel.setVisible(true);
        
 
   
        
        inquieriess.setBackground(new  java.awt.Color(34 ,45,49));
        realPanelconsultations.setVisible(false);
        
        admin.setBackground(new  java.awt.Color(34 ,45,49));
        PanelAdmin.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void roomw3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomw3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roomw3MouseClicked

    private void roomw2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomw2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roomw2MouseClicked

    private void reserva2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reserva2MouseClicked

    }//GEN-LAST:event_reserva2MouseClicked

    private void reserva1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reserva1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reserva1MouseClicked

    private void roomw1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomw1MouseClicked

    }//GEN-LAST:event_roomw1MouseClicked

    private void roomw4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomw4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roomw4MouseClicked

    private void roomw5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomw5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roomw5MouseClicked

    private void roomw6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomw6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roomw6MouseClicked

    private void roomw7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomw7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roomw7MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        
        Query02OfferView newframe51470 = new Query02OfferView();
        newframe51470.setVisible(true);
        
        
        
       
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        People newframe514 = new People();
        newframe514.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Ranking newframe99 = new Ranking();
        newframe99.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        tophotel newframe5149 = new tophotel();
        newframe5149.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void parameter1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parameter1MouseClicked
        Parameters newframe112 = new Parameters();
        newframe112.setVisible(true);
    }//GEN-LAST:event_parameter1MouseClicked

    private void book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book1ActionPerformed
        createAdmin newframe11 = new createAdmin();
        newframe11.setVisible(true);
    }//GEN-LAST:event_book1ActionPerformed

    private void book3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book3ActionPerformed
        deleteAdmin newframe514 = new deleteAdmin();
        newframe514.setVisible(true);
    }//GEN-LAST:event_book3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new master().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAdmin;
    private javax.swing.JPanel PanelCreateHotel;
    private javax.swing.JPanel PanelDeleteHotel;
    private javax.swing.JPanel PanelParameters;
    private javax.swing.JLabel admin;
    private javax.swing.JButton book1;
    private javax.swing.JButton book3;
    private javax.swing.JLabel inquieriess;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel parameter1;
    private javax.swing.JPanel realPanelconsultations;
    private javax.swing.JLabel reserva1;
    private javax.swing.JLabel reserva2;
    private javax.swing.JLabel roomw1;
    private javax.swing.JLabel roomw2;
    private javax.swing.JLabel roomw3;
    private javax.swing.JLabel roomw4;
    private javax.swing.JLabel roomw5;
    private javax.swing.JLabel roomw6;
    private javax.swing.JLabel roomw7;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables
}
